parameters:
#    unoegohh_mailer.example.class: Unoegohh\MailerBundle\Example

services:
#    unoegohh_mailer.example:
#        class: %unoegohh_mailer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
